### ISSUE TITLE
New Dataset

### ISSUE THREAD

**Issue by sweetpeach** [exnlpdatasets/exnlpdatasets.github.io#5]
Explanation type: highlight
Dataset name: Hummingbird
Link to the associated publication/preprint: https://arxiv.org/abs/2109.02738
Associated task: style classification (sentiment, politeness, offensiveness, emotions)
Granurality restriction (for highlights): words
Collection method: crowd
Number of instances: 500 sentences
Number of explanations per instance: 1
Total number of annotators: 3 annotators/sentence, 622 workers
Language: English

**Comment by amarasovic** [comment]
Thanks for contributing, your dataset is added.
