### ISSUE TITLE
New dataset (Explainable Quality Estimation)

### ISSUE THREAD

**Issue by plkumjorn** [exnlpdatasets/exnlpdatasets.github.io#6]
Hi, thank you for creating this helpful website. I'd like to add a new dataset concerning explanations for quality estimation of machine translation, as detailed below.

- Explanation type: highlights
- Dataset name: X-QE
- Link to the associated publication/preprint: https://aclanthology.org/2021.eval4nlp-1.17/
- Associated task: Quality Estimation of Machine Translation
- Granurality restriction (for highlights): words
- Collection method: experts
- Number of instances: 4590
- Number of explanations per instance: 1
- Total number of annotators: 14
- Language: 4 Language pairs -- Estonian-English (Et-En), Romanian-English (Ro-En), German-Chinese (De-Zh), Russian-German (Ru-De)

**Comment by sarahwie** [comment]
Thanks for your contribution, and I was excited to see this shared task at EMNLP! Added to table.
