### ISSUE TITLE
Dataset to add: COPA-SSE

### ISSUE THREAD

**Issue by a-brassard** [exnlpdatasets/exnlpdatasets.github.io#8]
Hi there! We created a new explanation dataset for COPA ([Balanced COPA](https://balanced-copa.github.io/) variant) and we'd love to be added to the list. I'm presenting it next week at LREC 2022 :) 

- Explanation type: semi-structured*
- Dataset name: [COPA-SSE](https://github.com/a-brassard/copa-sse) (Semi-Structured Explanations for COPA)
- Paper link: https://arxiv.org/abs/2201.06777
- Associated task: Balanced COPA (commonsense QA, causal reasoning)
- Granularity restriction: n/a
- Collection method: crowdsourcing
- Number of instances: 1500
- Number of explanations per instance: 4 to 9 (9747 total)
- Total number of annotators: n/a
- Language: English

*ConceptNet-like triples with free-form head and tail concepts. I'd maybe class this as structured but it's not very rigid and can also be used as free text.

**Comment by amarasovic** [comment]
Added to both Structured and Free-Text. Thanks!
